apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: previews
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: previews
  source:
    repoURL: https://github.com/anais-codefresh/tutorial-python.git
    targetRevision: HEAD
    path: charts/rookout-example
  destination:
    server: https://kubernetes.default.svc
    namespace: previews